### ISSUE TITLE
missing requirement in readme

### ISSUE THREAD

**Issue by Um9i** [d7415/merlin#10]
[future](https://pypi.org/project/future/) is a now requirement due to #https://github.com/d7415/merlin/commit/135dad1417e833aac7f3a56f07c4cc628d59770f

`from builtins import str`

**Comment by d7415** [comment]
Good spot, thanks. I'm not entirely sure that it's actually needed, but it won't run in its current state without it, so I've updated the README (in `master`, anyway).

The whole thing needs a proper py3 migration at some point.
