### ISSUE TITLE
Scan Parsing

### ISSUE THREAD

**Issue by Hardware-Hacks** [d7415/merlin#4]
For some reason sometimes scans do not parse to the via entering them in the website lookup bar.

My only guess is that maybe the regex is getting confused when fleet names are called "attack", "defend" and also some strange characters like =-!

This one didnt parse:
http://game.planetarion.com/showscan.pl?scan_id=g262t2jtte82g2w
 but it did when it was pasted directly to the bot in pm.

**Comment by d7415** [comment]
Were you pasting the scan URL in the lookup bar?

**Comment by Hardware-Hacks** [comment]
Yea, weird...

**Comment by d7415** [comment]
As everything the lookup box does scan-wise is the same as the bot (it actually loads the regex and function from the bot's code) I'm going to close this. If it happens again we can try to track something down.
