### ISSUE TITLE
Historical Dumps - Missing?

### ISSUE THREAD

**Issue by ImTheDeveloper** [d7415/merlin#8]
Installed a fresh bot today and during catch up hit a bunch of errors after tick 1015. I've had a look through and excal attempts to do the catch up of ticks from the alt url https://dumps.dfwtk.com/1030/planet_listing.txt this then causes failures as the dumps are missing.

1. I assume if in future rounds I choose to store dumps locally this issue wouldnt happen?
2. Bot is currently stuck in an infinite loop trying to catch up the logs and failing each tick resulting in:

```It is currently tick 1015 (8h 49m ago - Tue 28/11 09:01 UTC)```

and dumplog spewing out:
```Dump files missing looking for newer...```

**Comment by ImTheDeveloper** [comment]
I've turned catchup to false in merlin.cfg and this has fixed.

**Comment by d7415** [comment]
Hi,

Sorry, the dump archive ran out of disk space. That should be fixed now.
